import Head from "next/head";
import dynamic from "next/dynamic";
import Navbar from "@/components/user/utils/Navbar";
import Footer from "@/components/user/utils/Footer";
import Header from "@/components/user/utils/Header";
import Services from "@/components/user/utils/Services";
import Detail from "@/components/user/utils/Detail";
import Counter from "@/components/user/utils/Counter";
import About from "@/components/user/utils/About";
import Produk from "@/components/user/Produk";
import PostProject from "@/components/user/Project";


const ChatBot = dynamic(() => import("@/components/chatbot"), { ssr: false });

export default function Home() { 
  return (
    <> 
      <Head>
        <title>Kita Bisa Jual</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/kitabisajual.ico" />
      </Head>
      <div className="bg-primary">
        <Navbar />
        <Header />
        <About />
        <Services />
        <Produk />
        <Detail />
        <PostProject/>
        <Counter />
        <Footer />
        <ChatBot />
      </div>
    </>
  );
}
